# Individual Project 2 - NumPy
## Tess Anderson
### Version 1
#### Spring 2023 - DS160

In [6]:
# a. create a 2-by-2 NumPy array with the elements 10,20,30,40. 
import numpy as np
arrayA=np.array([10,20,30,40]).reshape((2,2))
arrayA

array([[10, 20],
       [30, 40]])

In [10]:
# i. square every element of the array:
np.square(arrayA)

array([[ 100,  400],
       [ 900, 1600]])

In [11]:
# ii. add 100 to every element of the array:
np.add(arrayA,100)

array([[110, 120],
       [130, 140]])

In [12]:
# iii. multiply every element of the array by 5:
np.multiply(arrayA,5)

array([[ 50, 100],
       [150, 200]])

In [13]:
#iv. calculate the sqaure root of each element in the array:
np.sqrt(arrayA)

array([[3.16227766, 4.47213595],
       [5.47722558, 6.32455532]])

In [18]:
# b. create a 3-by-3 array containing integers from 3 to 27 in multiples of 3.
array1=np.arange(3,28,3).reshape(3,3)
array1

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

In [33]:
# b. (continued) create a second array with 9 elements evenly spaced between 10 and 20
array2=np.arange(10,19).reshape(3,3)
array2

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [34]:
# b. (continued) multiply these arrays and display the output:
np.multiply(array1,array2)

array([[ 30,  66, 108],
       [156, 210, 270],
       [336, 408, 486]])

In [38]:
# c. read the files in and stack them into a unified dataset
p1=np.load('process1.npy')
p2=np.load('process2.npy')
p3=np.load('process3.npy')
p4=np.load('process4.npy')
p5=np.load('process5.npy')

In [49]:
UnifiedDataset=np.vstack((p1,p2,p3,p4,p5))
print(UnifiedDataset)
print('The means for each column are:',np.mean(UnifiedDataset,axis=0))

[[52 12 81  0 58]
 [96  4 61 16 43]
 [38 96 45 17 58]
 [97 21 22 25  6]
 [77  6 19  2 74]]
The means for each column are: [72.  27.8 45.6 12.  47.8]
